pipeline {
    options {
        buildDiscarder logRotator(numToKeepStr: '3')
    }
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mkdir build && cd build'
                sh 'cmake CMakeLists.txt'
                sh 'cmake --build .'
                sh 'ls -a'
            }
        }
        stage('Test') {
            steps {
                sh 'ctest'
            }
        }
    }
}